Fixed issues in Drizzle and Contract Events guide
trufflesuite/trufflesuite.com pull request #1113
Opened 2021-12-15 04:04 UTC by dkillen

Fixed issues in Drizzle and Contract Events guide reported in issue [#1076](https://github.com/trufflesuite/trufflesuite.com/issues/1076)

- Fixed broken links and typos.
- Added further description to ensure that it is clear to a user which files are being edited.
- Added examples of completed course code for comparison.
- Changed markdown heading levels so that table of contents displays on the sidebar.
- Removed unnecessary line breaks.

**Note:** The linked demo project now differs from the code produced by following the guide. The Issue #1076 reported a problem in the App.js file which is actually an issue in the demo project which lives in a different [repository](https://github.com/trufflesuite/drizzle-event-demo).

Resolves #1076

2021-12-15 04:38 UTC, fainashalts requested changes
Looks great! Had a couple tiny suggestions. Thanks!

2021-12-15 04:38 UTC, fainashalts commented on src/guides/drizzle-and-contract-events/index.md
> +In `./app/src/middleware/index.js` import `EventActions` and `generateStore` from Drizzle as well as
```suggestion
In `./app/src/middleware/index.js`, import `EventActions` and `generateStore` from Drizzle as well as
```

2021-12-15 04:38 UTC, fainashalts commented on src/guides/drizzle-and-contract-events/index.md
> +You completed `App.js` file should looks something like this:
```suggestion
Your completed `App.js` file should looks something like this:
```

2021-12-15 04:38 UTC, fainashalts commented on src/guides/drizzle-and-contract-events/index.md
>      1. MetaMask should NOT be on Main net! Do not run this if you're on main
```suggestion
    1. MetaMask should NOT be on Mainnet! Do not run this if you're on Mainnet!
```

2021-12-15 04:38 UTC, fainashalts commented on src/guides/drizzle-and-contract-events/index.md
>         net!
```suggestion
```

2021-12-17 22:24 UTC, dkillen commented
@cds-amal I have removed the leading $ from the cli commands.

2021-12-17 23:20 UTC, cds-amal approved these changes

2021-12-17 23:21 UTC, cds-amal commented
Thanks @dkillen.

2022-01-03 17:22 UTC, fainashalts approved these changes
One small suggested change, otherwise this looks great to me! @cds-amal I see you had requested changes, I believe they have been addressed?

2022-01-03 17:22 UTC, fainashalts commented on src/guides/drizzle-and-contract-events/index.md
> +The action `EventActions.EVENT_FIRED` is emitted whenever a contract event is detected in a Block. We will gain access to it by registering a custom middleware with the Redux store. As you may know,
I feel like Block doesn't need to be capitalized? But if it also capitalized elsewhere please ignore this!

```suggestion
The action `EventActions.EVENT_FIRED` is emitted whenever a contract event is detected in a block. We will gain access to it by registering a custom middleware with the Redux store. As you may know, Redux middleware comprises a set of functions, executed in a sequence, that process each dispatched action before passing it to Reducers. Add the following:
```

2022-01-03 23:06 UTC, merged