Update the Ethereum Overview documentation #1073
trufflesuite/trufflesuite.com pull request #1114
Opened 2021-12-15 18:41 UTC by kevinweaver

## Problem
[Issue 1073](https://github.com/trufflesuite/trufflesuite.com/issues/1073)

## Solution
Update the Ethereum Overview doc

2021-12-16 23:22 UTC, cds-amal requested changes
This is much improved @kevinweaver . I think the first graphic can be utilized differently to convey trust points, and left some other minor feedback.

2021-12-16 23:22 UTC, cds-amal commented on src/guides/ethereum-overview/index.md
> +In computer science terms, Ethereum is a "Turing complete", virtual machine. Simply put, Ethereum is an internet-based computer - A single symbolic computer that runs on thousands of physical compute
I don't get what a single symbolic computer is :/ Also, not everyone will know what Turing complete is, and we should give a little more explanation?

2021-12-16 23:22 UTC, cds-amal commented on src/guides/ethereum-overview/index.md
> +A sidechain network is a copy of Ethereum and a scaling solution that utilizes its own set of validating nodes, its own consensus mechanism, and therefore offers its own security assurances separate
```suggestion
A sidechain network is a copy of Ethereum and a scaling solution that utilizes its own validating nodes and consensus mechanism, offering its own security assurances separate from those provided by Ethereum.
```

2021-12-16 23:22 UTC, cds-amal commented on src/guides/ethereum-overview/index.md
> +- Marketplaces
No mention of DAOs?

2021-12-17 20:49 UTC, kevinweaver commented on src/guides/ethereum-overview/index.md
> +- Marketplaces
Added this and another couple.

2021-12-17 23:24 UTC, cds-amal commented on src/guides/ethereum-overview/index.md
> +
I meant adding text to explain the trust lines in the image, because it seems unnecessary. Read the rendered page and see. Maybe I'm wrong?

2022-01-10 18:22 UTC, kevinweaver commented
In conversation with @cds-amal, we agreed that the purpose of this document would be better fulfilled with a new doc focused more on answering the question "why truffle" and less on "why ethereum".

Until that new doc is written and this old doc is sunset, do we want to:

1. Leave this doc as-is for posterity and close this PR.
2. Consider this PR a slight improvement over the existing version and merge this.

@cds-amal suggested 1, I'm more open to 2, likely due to the bias of having put time into this revision.

2023-03-29 23:04 UTC, closed without merging