Optimization Site Audit report
trufflesuite/trufflesuite.com pull request #1177
Opened 2022-02-17 08:17 UTC by davidnguyen88

2022-03-15 18:30 UTC, davidmurdoch requested changes

2022-03-15 18:30 UTC, davidmurdoch commented on src/events/index.md
> +description: Truffle Events
```suggestion
```

2022-03-15 18:30 UTC, davidmurdoch commented on src/policy/index.md
> +description: This privacy policy (“Policy”) describes how ConsenSys Software Inc.
```suggestion
```

2022-03-21 17:19 UTC, jlazoff commented
Hi @davidmurdoch , 

Thank you for your code review above. @davidnguyen88 will be looking into them, and applying them globally. Thank you @davidnguyen88 and @cuonglt-ync for your work on this ticket. 

@davidmurdoch @kevinbluer : Sunny, Dana and I were debugging an issue flagged by GSC. None of the pages on the site were being indexed. Upon further inspection, I found that there is a deep tangle to issues on how the pages are being redirected, and used. I have written a couple of examples, and then will propose a plan to fix this issue. Our team can help you standardize this all. 

1. There is a 301 Permanent Redirect from trufflesuite.com/docs to trufflesuite.com/docs/ - this is permanent, and good, since we will want to have all pages standardized with a "/" ending, except the homepage. 
2. The canonical URLs of all the pages have to be modified to the new "/" ending. At the moment the canonical URL includes a "/index.html" ending. Here is a map of the URL endings I was able to find, and their behavior:

- Canonical is always: <link rel="canonical" href="https://trufflesuite.com/guides/index.html">
- https://trufflesuite.com/guides/index.html - link used on menu
- https://trufflesuite.com/guides/ - works
- https://trufflesuite.com/guides redirects to https://trufflesuite.com/guides/
- https://trufflesuite.com/guides.html - does not work in this case, but does in others 
- The sitemap includes the https://trufflesuite.com/guides/index.html invalidating all the URLs on Google Search Console

Here is a way to standardize and save each pages SEO power:

Our goal is to have every page, expect the homepage, with a "/" ending, such as: https://trufflesuite.com/guides/

2022-03-21 17:34 UTC, jlazoff commented
Hi @kevinbluer,
Can you share securely with @cuonglt-ync the following:

![Screen Shot 2022-03-21 at 17 50 27](https://user-images.githubusercontent.com/13966291/159331054-0581bcdd-0df4-4b95-be31-d99b3c2b585c.png)

Appreciate your help!,
Joshua

2022-03-21 18:15 UTC, davidmurdoch commented
@jlazoff I'm working accessibility changes in a new branch. This includes changes to the default URLs (canonicalizing the directory "/" as opposed to `index.html`). I'll take care of all of the changes you've requested above and ping you when it's ready. Thanks!

2022-03-21 18:47 UTC, jlazoff commented
> @jlazoff I'm working accessibility changes in a new branch. This includes changes to the default URLs (canonicalizing the directory "/" as opposed to `index.html`). I'll take care of all of the changes you've requested above and ping you when it's ready. Thanks!

Excellent, thank you for the update @davidmurdoch ! @cuonglt-ync  @davidnguyen88 Please pause on working on this ticket if/when @davidmurdoch finishes his branch. @davidmurdoch we are happy to re-scan the site once live and further iterate 🥇 

Thank you everyone!

2022-04-07 17:46 UTC, merged

2022-04-07 19:30 UTC, jlazoff commented
Excellent, thank you @davidmurdoch !

Tagging Sunny to keep him in the loop. 

Truffle is one step closer to optimization!