VSCode extension content restructure + updates
trufflesuite/trufflesuite.com pull request #1331
Opened 2022-10-12 19:00 UTC by alexandratran

VSCode extension content restructure + updates

2022-10-26 19:02 UTC, kevinbluer requested changes
Hey @alexandratran, few minor tweaks, although overall it's looking great 🙏

2022-10-27 02:12 UTC, OnlyOneJMJQ commented
Does mkdocs take care of 501 redirects or do we need to add those manually?

2022-10-27 04:06 UTC, kevinbluer commented
We're using a plugin ([mkdocs-redirects](https://github.com/datarobot/mkdocs-redirects)) to handle them, example of how they're specified [here](https://github.com/trufflesuite/trufflesuite.com/blob/136f23372f7d1e6fcdef2c3ad62b6e6c7c7bd483/mkdocs.yml#L75).

2022-10-27 19:32 UTC, rolandtyler approved these changes
A few small comments, but nothing breaking. LGTM

2022-10-27 19:32 UTC, rolandtyler commented on src/docs/vscode-ext/how-to/add-a-wallet.md
> +    configuration.
I'm getting hung up on "deploy contracts". Are the users selecting something called **deploy contracts** or are they selecting "contracts to deploy"? Or should it be "to deploy contracts?"

2022-10-27 19:32 UTC, rolandtyler commented on src/docs/vscode-ext/how-to/add-a-wallet.md
> +    provider must be added manually.
```suggestion
1. To deploy to another target that has been manually added to the Truffle configuration, you must add the
    provider manually.
```
Avoiding passive voice

2022-10-27 19:32 UTC, rolandtyler commented on src/docs/vscode-ext/quickstart.md
> +1. Press enter.
```suggestion
1. Press **enter**.
```

2022-10-27 19:32 UTC, rolandtyler commented on src/docs/vscode-ext/reference/command-palette.md
> +These features are enabled through the command palette and several "right-click" shortcut menus.
Both "right-click" and "right click" are used. WSG uses "right-click" as the action.

2022-10-27 19:57 UTC, kevinbluer approved these changes
Other than the link issue it's good to go 👍

2022-10-27 19:57 UTC, kevinbluer commented on src/docs/vscode-ext/how-to/debug-smart-contracts.md
> +included in the [Metacoin box](../../../boxes/metacoin/index.md)), you must invoke them first
This link to the box is broken (just needs to be `/boxes/metacoin`)

2022-10-27 20:55 UTC, merged