Guides + edits
trufflesuite/trufflesuite.com pull request #1395
Opened 2023-01-29 21:48 UTC by emilyJLin95

Push guide
Lens guide
Cleaning up marketplace tests

2023-02-07 20:19 UTC, kevinbluer reviewed
Some initial feedback to the Lens guide. Figured I'd submit this first and will get to the Push guide review momentarily.

2023-02-07 20:19 UTC, kevinbluer commented on src/guides/lens-protocol/index.md
> +The first failure is expected because we intentionally input the wrong password!
Optional...I feel like it ends a little abruptly, might be useful to briefly summarize what's just been and possibly some ideas for additional extensions?

2023-02-08 16:28 UTC, kevinbluer requested changes
Awesome content as always. Although there's a few necessary changes (particularly the broken YT embed, links from the top-level `unleashed` page, etc).

2023-02-08 16:28 UTC, kevinbluer commented on src/guides/push-notification/index.md
> +In this guide, we'll be adding some details to improve the user expriecnce: using Push to send decentralized notifications whenever a user's rental has expired. Additionally, we'll be using `ganache`
Typo on "expriecnce"

2023-02-08 16:28 UTC, kevinbluer commented on src/guides/push-notification/index.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed/oevGLIvWDTc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
Video isn't displaying for me (not sure if it's because it's in a deployment preview, although don't see why that would make a difference)?

2023-02-08 16:28 UTC, kevinbluer commented on src/guides/push-notification/index.md
> +Watch the livestream on [YouTube](https://youtu.be/oevGLIvWDTc) for a more in-depth walkthrough and to hear from core dev, Fabio, about how Push is changing up Web3 communication!
Similarly the YT link isn't working ("_This video isn't available anymore_")

2023-02-08 16:28 UTC, kevinbluer commented on src/guides/push-notification/index.md
> +The completed code lives [here](https://github.com/trufflesuite/unleashed_nft_rental_marketplace/tree/push).
GH link is broken: https://github.com/trufflesuite/unleashed_nft_rental_marketplace/tree/push Is it supposed to be https://github.com/trufflesuite/unleashed_nft_rental_marketplace/tree/push-notification?

2023-02-08 16:28 UTC, kevinbluer commented on src/guides/push-notification/index.md
> +## Deploy the Marketplace contract and add it as delegate
"add it as **a** delegate"?

2023-02-08 16:28 UTC, kevinbluer commented on src/unleashed/index.md
> +                    <a href="/guides/metamask-snap" class="btn btn-truffle text-decoration-none">DISCOVER MORE</a>
This link is pointing to the `metamask-snap` guide

2023-02-08 16:28 UTC, kevinbluer commented on src/unleashed/index.md
> +                    <a href="/guides/metamask-snap" class="btn btn-truffle text-decoration-none">DISCOVER MORE</a>
This one too (pointing to the `metamask-snap` guide) 🙃

2023-02-09 15:55 UTC, emilyJLin95 commented on src/guides/lens-protocol/index.md
> +The Lens box code lives [here](https://github.com/emilyJLin95/lens-box).
I put it there cause I wasn't sure if we wanted to make it truffle official due to maintenance
But yeah I can push to the truffle-box repo

2023-02-09 16:44 UTC, emilyJLin95 commented on src/guides/lens-protocol/index.md
> +    Finally, to get our token, we need to issue a challenge and get the user to sign it using their wallet. To do so, we'll be using the `challenge` and `authenticate` queries we created in `api.js`.
I meant for that tab to be there because it falls underneath the code explanation for number 3

2023-02-10 16:32 UTC, kevinbluer commented on src/guides/lens-protocol/index.md
> +The Lens box code lives [here](https://github.com/emilyJLin95/lens-box).
👍

2023-02-10 16:38 UTC, kevinbluer approved these changes
Looking great!

2023-02-10 16:39 UTC, merged