docs: fix typos
trufflesuite/trufflesuite.com pull request #1433
Opened 2023-07-13 14:35 UTC by pgrimaud

Hey :wave:,

This PR will fix :

1 typo in `src/blog/crytic-continuous-assurance-for-smart-contracts/index.md`
1 typo in `src/blog/the-infura-sdk-nft-truffle-box-all-you-need-to-know/index.md`
1 typo in `src/docs/truffle/reference/contract-abstractions.md`
1 typo in `src/guides/lens-protocol/index.md`
1 typo in `src/guides/rentable-nft/index.md`
1 typo in `src/guides/truffle-and-metamask/index.md`

Best!

2023-07-13 17:39 UTC, haltman-at requested changes
Thanks for this!  But the first of these typos is deliberate and should be reverted back to the mistaken way.  Other than that looks good!

2023-07-13 17:39 UTC, haltman-at commented on src/blog/crytic-continuous-assurance-for-smart-contracts/index.md
> +A careful reader will notice the vulnerability here: `function constructor` creates a public function (with a typo!) that is callable by anyone instead of being run only at initialization. Crytic wil
In this case, the typo is deliberate.

2023-07-13 17:40 UTC, cliffoo approved these changes
Thanks! (See Harry's review)

2023-07-13 18:28 UTC, pgrimaud commented on src/blog/crytic-continuous-assurance-for-smart-contracts/index.md
> +A careful reader will notice the vulnerability here: `function constructor` creates a public function (with a typo!) that is callable by anyone instead of being run only at initialization. Crytic wil
Oops, my bad. I just fixed it. 🥴

2023-07-14 02:10 UTC, haltman-at approved these changes

2023-07-14 02:10 UTC, haltman-at commented
Thanks again!

2023-07-14 02:10 UTC, merged